# Generated by Django 3.1.2 on 2020-10-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20201005_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalumni',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/'),
        ),
    ]
