# Generated by Django 3.1.2 on 2020-10-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_addalumni_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addalumni',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='dp/'),
        ),
    ]
