# Generated by Django 3.1.2 on 2020-10-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_auto_20201006_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addalumni',
            old_name='profile_pic',
            new_name='dp',
        ),
    ]
