# Generated by Django 3.1.2 on 2020-10-06 10:39

import alumni.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_auto_20201006_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addalumni',
            old_name='cur_address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='addalumni',
            old_name='cur_status',
            new_name='profession',
        ),
        migrations.AlterField(
            model_name='addalumni',
            name='batch',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(1984), alumni.models.max_value_current_year]),
        ),
    ]
