# Generated by Django 3.1.2 on 2020-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_auto_20201006_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='addalumni',
            name='icoInsta',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
