# Generated by Django 3.1.2 on 2020-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_addalumni_icoinsta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addalumni',
            name='dp',
            field=models.ImageField(blank=True, null=True, upload_to='dp/'),
        ),
    ]
