# Generated by Django 3.1.2 on 2020-10-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_homeslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('src', models.ImageField(blank=True, upload_to='notice/')),
            ],
        ),
    ]
